function ChiAvan(BoomInfo,YOUT,TOUT)
chi= YOUT(:,6).*BoomInfo.Pianta.l*cos(BoomInfo.Pianta.freccia)/(vecnorm(YOUT(:,7:9)'))';
V=(vecnorm(YOUT(:,7:9)'))';
figure(20)
plot(TOUT(:),chi);
title('time vs $\chi$','Interpreter','latex');
xlabel('t [s]');
ylabel('$\chi$','Interpreter','latex');
figure(21)
plot(TOUT(:),V);
title('Velocità');



% Grafico
linecolors={'r' 'y'};
[handles]=plotNy(TOUT(:),YOUT(:,6),1,...
    TOUT(:),YOUT(:,12),2,...
    'YAxisLabels',{ 'Angular Rate [rad/s]' 'Position [m]'},...
    'Linewidth',1,...
    'XLim',[0,TOUT(end)],...
    'XAxisLabel','time[s]',...
    'TitleStr','Autorotazione',...
    'FontSize',10,...
    'LegendString',{ 'r' 'z' });
grid on


% Grafico
linecolors={'r' 'y' 'c' };
[handles]=plotNy(TOUT(:),YOUT(:,4),1,...
    TOUT(:),YOUT(:,5),1,...
    TOUT(:),YOUT(:,6),1,...
    'YAxisLabels',{ 'Angular Rate [rad/s]'},...
    'Linewidth',1,...
    'XLim',[0,TOUT(end)],...
    'XAxisLabel','time[s]',...
    'TitleStr','Comportamento Oscillatorio',...
    'FontSize',10,...
    'LegendString',{ 'p' 'q' 'r'});
grid on
end

